### ISSUE TITLE
에디터/링크프리뷰/파일첨부

### ISSUE THREAD

**Issue by ngongon** [iKoru/ssam#9]
링크 프리뷰 - 맨 처음 나온 링크를 게시물 하단에 표시
1. 텍스트에서 http://snulife.com 링크시 별도로 링크 표시를 할 때만 프리뷰 제공 링크가 되는가?(에디터에 기능 존재)
2. 아니면 그냥 http://snulife.com 링크만 읽어서 하면 될지?
3. http://snulife.com snulife.com
깃헙처럼 그냥 스트링 파싱해서 하는 경우 문제는 http://snulife.com/처럼 띄어쓰기 안하면..

**Comment by ngongon** [comment]
상단 바에 넣을 기능 확정(본 깃 에디터처럼 무엇이 들어갈지)

**Comment by iKoru** [comment]
(개인적인 생각)
1번처럼 하면 제일 정확하고 깔끔하겠으나... UX가 안좋아진다는 단점이 있죠.. 아예 위지윅 형식으로 간다면 태그 아는 사람은 또 쓸 수 있겠지만 얼마나 쓸지는 미지수고
스트링 파싱하는게 최선인것같은데 띄어쓰기 문제는... 안고가야죠뭐 ㅜㅜ

**Comment by ngongon** [comment]
파일 첨부/이미지 첨부 방식 
-> 이미지는 drag/drop으로 binary로 바로 박히는 식으로 되더라구요
-> 파일 첨부는 vue-dropzone이든 vue-fineuploader이든 쓸 텐데, 이게 생각해보면 이미지 첨부된 것도 파일 첨부처럼 같이 보여야 할지? 아니면 첨부이미지랑 글삽입(drap/drop or 에디터 이미지첨부 이용한 경우)은 다르게 가는 것일지? (UI상으로나 업로드된 파일에 드래그한 이미지가 보이는 식일지) 정해야 할 것 같아요

**Comment by iKoru** [comment]
"가능하다면" 깃헙에서 되고있는 방식을 차용해도 될것같습니다. 
깃헙에서는 이미지든 첨부파일이든 첨부하면 에디터 상에는 짧게 id만 가져가도록 하고 링크만 걸어주는 식..? 구현이 어려울것같긴한데..

**Comment by ngongon** [comment]
1)vue-dropzone으로 퀼 에디터를 감싼(?)다
2)아래쪽에 파일 목록만 쭉 보여준다 (별도로 보여줘도 될듯 !?)

**Comment by ngongon** [comment]
<file-pond
        accepted-file-types="application/octet-stream, images/*, application/*"  
>
</file-pond>

예를 들어 .java파일을 허용하고 싶은데 안되네요 (안되는게 맞나..?!?!?) mime type으로 검색하여 실패.. 일단 패스..

**Comment by iKoru** [comment]
허용하는 확장자는 문서랑 이미지면 되는거같아요 ㅋㅋ .java파일을 커뮤니티에 올릴 사람은 없을테니..
문서는 ms office문서랑 hwp, txt 정도?면 되지않을까요?ㅋㅋ

**Comment by ngongon** [comment]
> 허용하는 확장자는 문서랑 이미지면 되는거같아요 ㅋㅋ .java파일을 커뮤니티에 올릴 사람은 없을테니..
> 문서는 ms office문서랑 hwp, txt 정도?면 되지않을까요?ㅋㅋ

- zip파일같은거도 다 해야 할 것 가틍ㄴ데 mime type만 나중에 검색해서 추가하면 될 것 같으므로 패스합니다..
- 단 나중에 서버는 별도로 하면 될 것 같고 manual 업로드로 한번에 올라가는 거 되구요 서버 부분만 나중에 보면 될 것 같아요... 
- 그리고 정해야 할게 첨부 파일들 보이는 방식? 기본형은 스크롤 아래로 쭉쭉 되서.. 이건 나중에 레이아웃 할 때 정해질 것이라 생각하고 패스합니다.. 
이제 이미지 처리 볼게요..
